# Generated by Django 3.0.8 on 2020-07-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lan',
            new_name='lng',
        ),
    ]
